FIX: removing last component deletes entity as well
benmoran56/esper pull request #83
Opened 2023-05-05 19:22 UTC by gretkierewicz

fixes #82

Due to boy scout rule, there are additional minor changes:
- add more explicit exceptions
- change return to removed component instead of entity

2023-05-05 20:03 UTC, gretkierewicz commented
@benmoran56  check this out pls 

I'm using pop() instead of del to return removed component but it should not have big performance impact overall

2023-05-09 08:41 UTC, benmoran56 requested changes
Looks good overall, but please rollback the `if` checks in `remove_component`.

2023-05-09 14:03 UTC, gretkierewicz commented on esper/__init__.py
>          """
Sure, done

2023-05-09 23:36 UTC, benmoran56 approved these changes
Thank you very much!

2023-05-09 23:36 UTC, merged

2023-05-09 23:37 UTC, benmoran56 commented
I'll try to get a point release out soon.